### ISSUE TITLE
[Bug] Re-login popup does not respond

### ISSUE THREAD

**Issue by ithieund** [alexkim205/Google-Drive-Electron#11]
After some weeks, it says 'You are not login, please re-login and refresh to continue'. I clicked the Re-Login link and it show a login popup, but after successfully login, it does not do any further actions. It stays there like hanging.

The expected bebhavior is to hide that popup and refresh the main windows automatically.
Thanks.

**Comment by alexkim205** [comment]
#13 duplicate
